### Create a new book
POST http://localhost:3000/books
Content-Type: application/json

{
  "name": "Money Heist",
  "author": "Claude N",
  "publicationYear": "2025",
  "isbn": "120"
}
### Get all books
GET http://localhost:3000/books

### Get one book by ID
GET http://localhost:3000/books/1

### Get book by ISBN
GET http://localhost:3000/books/isbn/100

### Count book by year
GET http://localhost:3000/books/count/2025

### Update a book
PATCH  http://localhost:3000/books/1
Content-Type: application/json

{
  "name": "Clean Code (Updated)",
  "author": "Robert C. Martin",
  "publishedYear": "2021",
  "isbn": "200"
}

### Soft delete a book
DELETE  http://localhost:3000/books/1

### Hard delete a book
DELETE http://localhost:3000/books/1/permanent
