### Create a new book
POST http://localhost:3000/books
Content-Type: application/json

{
  "name": "Brian Coden",
  "author": "Bruce Nyongesa",
  "publishedYear": 2018,
  "isbn": 970
}

### Get all books
GET http://localhost:3000/books

### Get one book by ID
GET http://localhost:3000/books/1

### Get book by ISBN
GET http://localhost:3000/books/isbn/97

### Update a book
PATCH  http://localhost:3000/books/1
Content-Type: application/json

{
  "name": "Clean Code (Updated)",
  "author": "Robert C. Martin",
  "publishedYear": 2009,
  "isbn": 9780132350884
}

### Soft delete a book
DELETE  http://localhost:3000/books/1

### Hard delete a book
DELETE http://localhost:3000/books/1/permanent
