### Create a new book
POST http://localhost:3000/books
Content-Type: application/json

{
  "name": "LOve scandal",
  "author": "Nyariki ",
  "publicationYear": "2025",
  "isbn": "400"
}
### Get all books
GET http://localhost:3000/books

### Get one book by ID
GET http://localhost:3000/books/5

### Get book by ISBN
GET http://localhost:3000/books/isbn/100

### Count book by year
GET http://localhost:3000/books/count/2025

### Update a book
PATCH  http://localhost:3000/books/4
Content-Type: application/json

{
  "name": "Dollar heist Code (Updated)",
  "author": "Bro code",
  "publishedYear": "2021",
  "isbn": "300"
}

### Soft delete a book
DELETE  http://localhost:3000/books/3

### Hard delete a book
DELETE http://localhost:3000/books/5/permanent
